### ISSUE TITLE
Demo recordings seem to be broken

### ISSUE THREAD

**Issue by flaki** [fernandojsg/aframe-teleport-controls#17]
https://fernandojsg.github.io/aframe-teleport-controls/multiple/?avatar-recording=recording.json

Console log reports:
```
TypeError: AFRAME.utils.throttle is not a function[Learn More]  aframe-motion-capture.min.js:1:938
```

**Comment by HAZARDU5** [comment]
I'm seeing the same thing in Chrome (v57.0.2987.133).

**Comment by HAZARDU5** [comment]
Just checked out the repository and tested locally and the above example seems to work. Perhaps the Github pages files are slightly out of date?

**Comment by fernandojsg** [comment]
It's working again https://fernandojsg.github.io/aframe-teleport-controls/examples/multiple/?avatar-recording=recording.json
