### ISSUE TITLE
Oculus Controllers? 

### ISSUE THREAD

**Issue by stevel4857** [fernandojsg/aframe-teleport-controls#18]
I can't seem to get this to work and yet I see the demos on aframe.io do work with my controllers. Is it me or is it that the component was modified by AFrame? If so can this be added into this?

**Comment by icgreen** [comment]
I second this issue. I've tried to change the default button to trigger and I still can't get it to work. Just as the person explain above, when I used demo's it works fine but I doesn't work when i try to code it up

**Comment by TonyViT** [comment]
I had the same issue. Using <script src="https://aframe.io/releases/0.5.0/aframe.min.js"></script> did the trick.
The issue is that now A-frame has reached version 0.6.1... I can't stick to ver0.5.0 only because of this package. And obviously I don't know why with newer A-frame versions it doesn't work. Has anyone an idea?

**Comment by fernandojsg** [comment]
I'll take a look to it to update to the latest version of aframe. thanks for reporting

**Comment by TonyViT** [comment]
You're welcome! Let us know when it's ready so that we can test it. Your package is awesome.

**Comment by kwadroke** [comment]
Also having a problem when using AFrame 0.6.0/0.6.1. Some of the other scripts I use require newer than 0.5.0.

**Comment by fernandojsg** [comment]
Updated to 0.7.0! Could you please give it a try and report back if you find some issue ;)

**Comment by TonyViT** [comment]
Ok, next weekend I'll give it a try

**Comment by TonyViT** [comment]
Hello Fernando, I've given it a try, but can't manage to make it work, both on Chromium and Firefox. Can you give me the sample code with which you verified that it does work? Maybe it's me that use it in a wrong way.

**Comment by stevel4857** [comment]
Still have the same issue. If I use AFrame 5 it works anything above 5 the Oculus controllers vanish.

**Comment by stevel4857** [comment]
Sorry. I actually forgot that I had made this an issue a while ago.

**Comment by fernandojsg** [comment]
Already added support for oculus, vive, daydream and gearvr on master. Please give it a try.
proof :) https://twitter.com/fernandojsg/status/925316146399719425

**Comment by TonyViT** [comment]
Hi @fernandojsg . I'm testing it with this code
`<head>
  <title>My A-Frame Scene</title>
  <script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>
  <script src="https://rawgit.com/fernandojsg/aframe-teleport-controls/master/dist/aframe-teleport-controls.min.js"></script>
</head>

<body>
  <a-scene>
    <a-entity id="cameraRig">
      
      <a-entity id="head" camera wasd-controls look-controls></a-entity>
      
      <a-entity id="left-hand" teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
      <a-entity id="right-hand" teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
      <a-plane id="plane" position="0 0 -2" rotation="-90 0 0" scale="5 5 5" color="#0000fe"></a-plane>
    </a-entity>
  </a-scene>
</body>`
Using Oculus Rift + Touch on Windows 10, Firefox 56.0.2 (64bit). Whatever button I press on the controllers, I can't activate the teleporting beam. Maybe it's me that can't use A-Frame or my PC is doomed, I don't know :)

**Comment by stevel4857** [comment]
I rewrote the code adding the missing HTML and placed it here: http://www.cablecenter.org/vr/teleport-test/

and it doesn't work for me.

**Comment by stevel4857** [comment]
My code:

`<html>
<head>
  <title>My A-Frame Scene</title>
  <script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>
  <script src="https://rawgit.com/fernandojsg/aframe-teleport-controls/master/dist/aframe-teleport-controls.min.js"></script>
</head>

<body>
  <a-scene>
    <a-entity id="cameraRig">
      
      <a-entity id="head" camera wasd-controls look-controls></a-entity>
      
      <a-entity id="left-hand" teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
      <a-entity id="right-hand" teleport-controls="cameraRig: #cameraRig; teleportOrigin: #head;"></a-entity>
      <a-plane id="plane" position="0 0 -2" rotation="-90 0 0" scale="5 5 5" color="#0000fe"></a-plane>
    </a-entity>
  </a-scene>
</body>
</html>`

**Comment by stevel4857** [comment]
It hasn't worked in a long time. I was hoping to create a holiday card and finish a virtual tour of our building but I'm essentially stuck. I think it's been 60 days now? I get that you're one person so I don't want to be mean but I will pay $50.00 for a working version. I could pay in bitcoin.

**Comment by stevel4857** [comment]
Here's what I did. http://www.cablecenter.org/vr/teleport-test/ is the code mentioned that is "supposed to work" and does not. 
http://www.cablecenter.org/vr/teleport-test/index2.html is the code I ripped from the build.js example. I copied the mappings.js file and the build.,js file and didn't use the aframe.js link and THAT WORKED. 

http://www.cablecenter.org/vr/teleport-test/index3.html  just had the mappings.js file but the aframe.js version 7 instead of the build.js. So, it is something different in the build.js compared to the  <script src="https://aframe.io/releases/0.7.0/aframe.min.js" script. So, for those that want it to work for now I recommend using the build.js file in place of the aframe script. The build file is in the download and easy to find.

**Comment by stevel4857** [comment]
FYI. In order to get teleport to work with the build.js file you also need the mappings.js file. Do not use both the aframe include and the build.js file because it will error out. The controllers will work. View the source on my file at http://www.cablecenter.org/vr/teleport-test/index2.html by right-clicking on the VR icon and viewing source. My question: can I add the controller mapping to the HTML code? I did try but possibly got the code wrong.

**Comment by TonyViT** [comment]
Stevel, I've tried your solution http://www.cablecenter.org/vr/teleport-test/index2.html and I confirm that it works, so you're on the right path

**Comment by stevel4857** [comment]
Thanks. My guess is that possibly this code:
<a-entity teleport-controls="startEvents: teleportstart; endEvents: teleportend; type: line"
        vive-controls="hand: right"
        microsoft-motion-controls="hand: right"
        oculus-touch-controls="hand: right;"
        daydream-controls="right" gearvr-controls="right">
      </a-entity>

Should look like:

<a-entity teleport-controls="startEvents: teleportstart; endEvents: teleportend; type: line"
        vive-controls="hand: right"
        microsoft-motion-controls="hand: right"
        oculus-touch-controls="hand: right; **thumbstickdown: teleportstart; thumbstickup:teleportend;**"
        daydream-controls="right" gearvr-controls="right">
      </a-entity>

**Comment by stevel4857** [comment]
Just to double check I added that code from the mappings.js file directly to the controller code and it didn't work. view-source:http://www.cablecenter.org/vr/teleport-test/index3.html

**Comment by TonyViT** [comment]
Waiting for @fernandojsg to help us in understanding the issue...

**Comment by stevel4857** [comment]
My assumption is that possibly the aframe master may work? I don't have
time to check now. Maybe aframe 7 doesn't have the updates in it?

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377

**Comment by stevel4857** [comment]
But it would be cool to be able to specify the buttons for each controller
manually within the asset code.

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377

**Comment by fernandojsg** [comment]
Sorry guys! I'll reopen the issue and check it again. I'm going to modify the current examples and build so they don't use `build.js` and use just the dist.

**Comment by fernandojsg** [comment]
@TonyViT @stevel4857 I've modified the examples so it uses just the `dist/` instead of the `build` as before. And I've deployed a new version of the examples https://fernandojsg.github.io/aframe-teleport-controls
Could you give it a try and let me know?
I've tried on oculus and vive and it's working as expected so far.

**Comment by stevel4857** [comment]
It works great! Thanks so much. You have no idea. I'm not sure if you get
enough praise for your work on this but thank you. Also, I am more than
willing to contribute to this. If you have a bitcoin wallet I'd be happy to
send you some.

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377

**Comment by TonyViT** [comment]
@fernandojsg I'll test them on Monday and I'llgive you another confirmation!

**Comment by TonyViT** [comment]
I confirm that the new samples that you've given us work like a charm with Oculus Touch! I've still some issues in creating a project from scratch, but maybe it is because I'm writing something bad. Thank you a lot and keep up your awesome work!

**Comment by fernandojsg** [comment]
@stevel4857 Happy to hear that it works for you ;) and thanks for the bitcoin offer! although I prefer that If you want to contribute anyhow please spend it in any opensource project you like or if you feel you could also use https://donate.mozilla.org ;)

@TonyViT happy to hear too! If you have any specific problem just drop a word in aframe slack or stackoverflow and I believe many people could help with your issue ;)

**Comment by stevel4857** [comment]
Thanks, Fernando, I'm actually writing code samples and giving them away on
CodePen. My plan next is to figure out the component code structure and
write some simple code showing people, like me, who don't understand the
explanation currently in aframe docs.
I actually learn faster by seeing real code examples but the "console"
explanation although a great start just isn't enough to learn how to
dynamically rewrite text from a clickable object and on and on.

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377
