### ISSUE TITLE
Walking as an option. 

### ISSUE THREAD

**Issue by stevel4857** [fernandojsg/aframe-teleport-controls#19]
I would like to be able to walk. The game Compound on Steam has this option and I would rather run than teleport. I have played hours in it without ever getting sick. I believe sickness comes from moving too fast. 
Anyway, I would like to be able to walk if I want as well as teleport. Thank you for working on this it is amazing.

**Comment by fernandojsg** [comment]
I believe that should be another separete component and I believe I've seen something like that already. You should just decide how to switch between these two
