### ISSUE TITLE
Controllers left behind when teleporting?

### ISSUE THREAD

**Issue by arcwhite** [fernandojsg/aframe-teleport-controls#2]
I've knocked together an example of this, see https://github.com/arcwhite/aframe-teleport-example

In short, when I try to include this in the browser (only, not using npm etc.) - most of the functionality works, up to the point where the camera teleports but the controllers do not!

I've tried the examples here on your site and they *do* consistently work on the same machine + browser, so I figure it's something specific about either the instructions for including this directly in browser, or the files as compiled into dist?

Either way, please let me know how I can help further!

**Comment by sirkitree** [comment]
Just tried installing this using the npm method tonight and I'm seeing the same problem.

**Comment by sirkitree** [comment]
Here is my repo so you can see my setup: https://github.com/LullabotVR/vrbp

**Comment by sirkitree** [comment]
Also here is a URL to check it out first hand in Chromium: https://lullabotvr.github.io/vrbp/

**Comment by sirkitree** [comment]
Strangely enough, running this locally the controllers are left behind, but running it on the url above, the teleportation doesn't work at all, thought eh hand controllers do show up...

**Comment by fernandojsg** [comment]
@arcwhite @sirkitree my fault, I didn't comment on the repo that this component needs the latest version of `aframe (0.4.0)` but as it not published yet on npm, `package.json` still has the current stable version which is causing the controllers to left behind when jumping.
`aframe 0.4.0` will be released by the next week, so I'll update the repo and everything should be fine, in the meantime you could use the master version of `aframe` repo currently versioned as `0.4.0`.
Sorry for the confusion!

**Comment by sirkitree** [comment]
Thanks! Updating to 0.4.0 worked!

**Comment by arcwhite** [comment]
Marking as closed, thanks @fernandojsg 👍
