### ISSUE TITLE
Daydream Support?

### ISSUE THREAD

**Issue by mokargas** [fernandojsg/aframe-teleport-controls#21]
Currently teleport-controls don't seem to work with daydream-controls in 0.6.0.

**Comment by HAZARDU5** [comment]
I'd love to see support for GearVR / Daydream added as I've got a couple of mobile demos where this component would be great for locomotion.

**Comment by LucidoM** [comment]
I have basic daydream support working in my fork, I've submitted a pull request [here].
(https://github.com/fernandojsg/aframe-teleport-controls/pull/22)

**Comment by fernandojsg** [comment]
Already added support for both daydream and gearvr on master. Please give it a try.
proof :) https://twitter.com/fernandojsg/status/925316146399719425
