### ISSUE TITLE
`button` property should be an array to support multiple controllers

### ISSUE THREAD

**Issue by ngokevin** [fernandojsg/aframe-teleport-controls#23]
e.g., `teleport-controls="button: menu, ybutton"`. The default such as `trackpad` would only work on Vive.

**Comment by fernandojsg** [comment]
That should be up to the application. We could have two controllers that has the same A button, but on one you would like to use the trackpad and on the other you would like to use the A button, so using `button: A, trackpad` will cause unexpected behaviour.

Look at how we use it on a-painter depending on the type of controller:

https://github.com/aframevr/a-painter/blob/af2fb4a80ad5ad1176c0269540185d8fe03c6a76/src/components/paint-controls.js#L52

https://github.com/aframevr/a-painter/blob/af2fb4a80ad5ad1176c0269540185d8fe03c6a76/src/components/paint-controls.js#L61
