### ISSUE TITLE
remove instances of `.clone` and `.getWorldPosition` from tick

### ISSUE THREAD

**Issue by ngokevin** [fernandojsg/aframe-teleport-controls#33]
`.clone` will create a vector, so several vectors created on each tick when active.

Instead of `vec3.copy(object3d.getWorldPosition())`, you can do `object3d.getWorldPosition(vec3)`, but always store it in a reusable vector.

**Comment by stevel4857** [comment]
Still can't get teleport component to work with Oculus after AFrame version
5. I downloaded the latest component and added  <script src="
https://aframe.io/releases/0.7.0/aframe.min.js"></script>
  <script src="
https://rawgit.com/fernandojsg/aframe-teleport-controls/master/dist/aframe-teleport-controls.min.js">
to the head and literally nothing appears. It's not the version of Aframe
so I assume it must be the change to the component?

Steve Luiting
http://sluiting.weebly.com
P: 720.563.9377
