### ISSUE TITLE
Teleport not in Oculus? 

### ISSUE THREAD

**Issue by stevel4857** [fernandojsg/aframe-teleport-controls#34]
I downloaded the latest component and redid the basic example and no controllers appear.

<!DOCTYPE html>
<html>
  <head>
     <script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>
  <script src="https://rawgit.com/fernandojsg/aframe-teleport-controls/master/dist/aframe-teleport-controls.min.js"></script>
    <script src="../common/shaders/skyGradient.js"></script>
  </head>
  <body style="background-color: #000">
    <a-scene>
      
      <a-entity id="sky"
                geometry="primitive: sphere; radius: 65;"
                material="shader: skyGradient; colorTop: #aaa; colorBottom: #fff; side: back"></a-entity>
      <a-entity id="floor"
                rotation="-90 0 0"
                geometry="primitive: plane; width: 100; height: 100"
                material="src: url(floor.jpg); repeat: 80 80">
      </a-entity>
      
      <a-entity teleport-controls vive-controls="hand: left"></a-entity>
      <a-entity teleport-controls="type: line" vive-controls="hand: right"></a-entity>
      </a-entity>
    </a-scene>
  </body>
</html>

**Comment by fernandojsg** [comment]
Duplicated https://github.com/fernandojsg/aframe-teleport-controls/issues/18
