### ISSUE TITLE
latest build the controllers don't follow the camera

### ISSUE THREAD

**Issue by ngokevin** [fernandojsg/aframe-teleport-controls#37]
Not using a camera rig, the controllers don't teleport/move with the camera after teleport. Did something change? Gonna try a camera rig instead though.

**Comment by fernandojsg** [comment]
Yep I just noticed that, sorry. I'll try to fix it today

**Comment by ngokevin** [comment]
Hm, teleport still broken for me, the hands still don't move.

**Comment by ngokevin** [comment]
I just switched to a camera rig

**Comment by fernandojsg** [comment]
@ngokevin I didn't updated the build maybe because of that? I'll try later anyway
