### ISSUE TITLE
examples broken, do not contain a-frame build

### ISSUE THREAD

**Issue by ngokevin** [fernandojsg/aframe-teleport-controls#41]
https://fernandojsg.github.io/aframe-teleport-controls/examples/basic/

**Comment by fernandojsg** [comment]
Updated, I forgot to use the `ghpages` command and I was just publishing the same as master O:) Here you have it working again: https://fernandojsg.github.io/aframe-teleport-controls/basic/
https://fernandojsg.github.io/aframe-teleport-controls
