### ISSUE TITLE
Show how to use without build.js? 

### ISSUE THREAD

**Issue by stevel4857** [fernandojsg/aframe-teleport-controls#45]
I tried to use your basic example including the aframe link and teleport component but no teleport works. Can you provide a working example without the build.js? Also, I appreciate the comment about being able to teleport on the environment by adding specify collisionEntities: .environmentGround but where and how? How exactly is this applied? A simple example would speed my learning curve 1000 percent. 

Thanks

**Comment by fernandojsg** [comment]
I've updated the current examples to work without build.js, please give it a try
