### ISSUE TITLE
Controller doesn't follow the user

### ISSUE THREAD

**Issue by rondagdag** [fernandojsg/aframe-teleport-controls#5]
Whenever I teleport, the controller doesn't follow the headset.
I'm using the same browser. It works here https://fernandojsg.github.io/aframe-teleport-controls/basic/
but not here http://codepen.io/rondagdag/pen/QGJmqo
Thanks,

Ron

**Comment by fernandojsg** [comment]
Please see the comments here: https://github.com/fernandojsg/aframe-teleport-controls/issues/2
As soon as 0.4.0 will be release (probably this week) it will be fixed.
