### ISSUE TITLE
broken on GearVR?

### ISSUE THREAD

**Issue by payamspot** [fernandojsg/aframe-teleport-controls#59]
i have changed nothing on my code, but teleport deosn't work on my GearVR with controller anymore!
This is the what i use for adding teleport to my code:

      <a-entity id="cameraRig">
              
            <a-camera></a-camera>
              
            <a-entity teleport-controls="cameraRig:#cameraRig; button:trigger; type:line; maxLength:44; defaultPlaneSize:999;"
                        laser-controls raycaster="objects:.hasEvent; interval:200; showLine:true;" line="color:#eee; opacity:0.2;" />
              
      </a-entity>

**Comment by vincentfretin** [comment]
What version of aframe are you using? What version of teleport?

**Comment by payamspot** [comment]
aframe 0.7.0
teleport master

**Comment by vincentfretin** [comment]
aframe 0.7.0 was having too much issues with the raycaster line, I'm currently using a post 0.7.1 version 2017-11-19 08:09
https://rawgit.com/aframevr/aframe/bfacbdc/dist/aframe-master.min.js
and teleport master

You should try aframe master, the soon to be released 0.8.0.

**Comment by payamspot** [comment]
it was working file last week, i have changed nothing, and now it doesn't work.
i guess gear vr is updated and change something.

**Comment by vincentfretin** [comment]
Ok. I can't test right now, I'll test this weekend to confirm on my GearVR.

**Comment by payamspot** [comment]
Thank you so much @vincentfretin 
I updated aframe to 0.7.1 and still teleport doesn't show.
And here is my code : https://codepen.io/payamspot/pen/xWKQyQ
Thanks again

**Comment by DougReeder** [comment]
Oculus Browser 4.3.0 has a bug where it ignores the Gear VR Controller.  If that's part of your problem, try with Samsung Internet for Gear VR (a separate app from the Samsung Internet for Android).

**Comment by payamspot** [comment]
That's true 👍 
Teleport (Controller) works in Samsung Browser, but not Oculus Browser.

**Comment by payamspot** [comment]
What should we do? Should we wait for Oculus to resolve the bug, or we can report it to them?

**Comment by DougReeder** [comment]
Oculus knows of the bug and has a fix for their next release, which is supposed to be in two weeks.

> On Mar 9, 2018, at 11:58 PM, Payam Rahmani <notifications@github.com> wrote:
> 
> What should we do? Should we wait for Oculus to resolve the bug, or we can report it to them?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Doug Reeder
reeder.29@gmail.com
https://twitter.com/reeder29
Recall your notes by context, with Serene Notes: https://serenenotes.hominidsoftware.com/
Make your smartphone work for you, not some company, with LuneOS: http://webos-ports.org/
