### ISSUE TITLE
Can't go further than a point

### ISSUE THREAD

**Issue by payamspot** [fernandojsg/aframe-teleport-controls#60]
aframe 0.8.0
gearvr with controller
i have a game. using WASD i can go as far as i want. but when i switch to VR mode, using teleport i can't go further than a point!

**Comment by donmccurdy** [comment]
You'll probably need to share a demo / code to get help with this, there is no hard limit built into this component.

**Comment by payamspot** [comment]
Sure. Thanks Don. here is my project remix: https://glitch.com/edit/#!/tmp002
It's not possible to go further than a point. For example to teleport till edge of the green plane (ground).

**Comment by donmccurdy** [comment]
If you're using the `collisionEntities` property, teleport controls will be able to go anywhere it can reach on those entities. Without `collisionEntities`, the default surface is a plane 100m in size. If you want to extend that, use `defaultPlaneSize: 250` or larger.

See: https://github.com/fernandojsg/aframe-teleport-controls#properties

**Comment by payamspot** [comment]
I'm not using collisionEntities in the example above. I used defaultPlanseSize before, but didn't help :|
I hope you had Gear VR with controller to test it yourself.
